# Generated by Django 2.2.5 on 2019-10-08 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191008_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 8, 19, 12, 34, 463991)),
        ),
    ]
