# Generated by Django 2.2.5 on 2019-10-09 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191009_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 12, 15, 9, 751291)),
        ),
    ]
